[package]
name = "slp_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slp_parse = { path = "../slp_parse" }
duckdb = "0.9.2"