[package]
name = "slpprocess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
num_enum = "0.6.1"
enumflags2 = "0.7.7"
nohash-hasher = "0.2.0"
rayon = "1.7.0"
peppi = { git = "https://github.com/hohav/peppi.git" }
bytemuck = "1.13.1"