use strum_macros::{Display, EnumString};

#[derive(Debug, Clone, Copy, Display, EnumString)]
pub enum Pre {
    FrameNumber,
    RandomSeed,
    ActionState,
    PositionX,
    PositionY,
    Orientation,
    JoystickX,
    JoystickY,
    CstickX,
    CstickY,
    EngineTrigger,
    EngineButtons,
    ControllerButtons,
    ControllerL,
    ControllerR,
    Percent,
}

#[derive(Debug, Clone, Copy, Display, EnumString)]
pub enum Post {
    FrameNumber,
    Character,
    ActionState,
    PositionX,
    PositionY,
    Orientation,
    Percent,
    ShieldHealth,
    LastAttackLanded,
    ComboCount,
    LastHitBy,
    Stocks,
    StateFrame,
    Flags1,
    Flags2,
    Flags3,
    Flags4,
    Flags5,
    MiscAS,
    IsGrounded,
    LastGroundID,
    JumpsRemaining,
    LCancel,
    HurtboxState,
    AirVelX,
    VelY,
    KnockbackX,
    KnockbackY,
    GroundVelX,
    HitlagRemaining,
    AnimationIndex,
}

#[derive(Debug, Clone, Copy, Display, EnumString)]
pub enum Item {
    FrameNumber,
    ItemID,
    State,
    Orientation,
    VelX,
    VelY,
    PositionX,
    PositionY,
    DamageTaken,
    ExpirationTimer,
    SpawnID,
    MissileType,
    TurnipType,
    IsLaunched,
    ChargePower,
    Owner,
}
